# TensorFlow Basics and XOR Problem

In [3]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] ='2' # for silencing warnings
import tensorflow as tf
import numpy as np
import math
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers

## 1. Tensorflow Basic

In [5]:
print(tf.__version__)
hello = tf.constant('Hello, TensorFlow') # 상수 텐서 생성
print(hello.numpy()) # hello 텐서의 값을 넘파이 배열로 변환하여 출력
tf.print(hello) # hello 텐서의 값 출력

2.11.0
b'Hello, TensorFlow'
Hello, TensorFlow


In [6]:
# Random number generation with uniform distribution
ru_num = tf.random.uniform([3,2],0,1) # 0부터 1 사이의 균일 분포를 따르는 난수로 구성된 3x2 형태의 텐서를 생성
tf.print(ru_num) 

[[0.867334 0.661256313]
 [0.751828074 0.215872288]
 [0.65317297 0.980561852]]


In [7]:
# Random number generation with normal distribution
rn_num = tf.random.normal([2,2,3],0,1) # 2x2x3 형태의 정규 분포(normal distribution)를 따르는 난수로 구성된 텐서 생성
tf.print(rn_num)

[[[-0.515627742 -1.92001951 0.67796123]
  [-0.261559904 0.401146263 -1.38758039]]

 [[0.711531043 1.17894244 -1.54037404]
  [0.114501804 -1.57900167 -0.551791]]]


In [9]:
def sigmo(x):
    """Sigmoid function"""
    return 1/(1+math.exp(-x))
print(sigmo(-5), sigmo(0), sigmo(5))

0.0066928509242848554 0.5 0.9933071490757153


In [10]:
x = 1; y = 0
w = tf.random.normal([1],0,1)
result = sigmo(x*w)
tf.print(w, result)

[0.628063619] 0.6520502641628829


In [11]:
# classification with sigmoid activation function: Case 1
alpha = 0.1 # 학습률(learning rate)로서 가중치 갱신 시 사용될 값
for i in range(1000):
    output = sigmo(x*w) # 입력(x)과 가중치(w)를 이용하여 출력(output) 계산
    error = y - output
    w = w + x*alpha*error # 가중치 갱신
    if i % 100 == 99:
        tf.print(f'{i}, {error:.5f}, {output:.5f}, {w}')

99, -0.11319, 0.11319, [-2.0699084]
199, -0.05528, 0.05528, [-2.8440723]
299, -0.03614, 0.03614, [-3.2870517]
399, -0.02676, 0.02676, [-3.5964742]
499, -0.02121, 0.02121, [-3.8339226]
599, -0.01756, 0.01756, [-4.026431]
699, -0.01497, 0.01497, [-4.1882396]
799, -0.01304, 0.01304, [-4.3277535]
899, -0.01155, 0.01155, [-4.4503555]
999, -0.01037, 0.01037, [-4.5596857]


In [12]:
# classification with sigmoid activation function: Case 2
x=0; y=1; alpha=0.1
w = tf.random.normal([1],0,1)
for i in range(1000):
    output = sigmo(x*w)
    error = y - output
    w = w + x*alpha*error
    if i % 100 == 99:
        tf.print(i, error, output, w)

99 0.5 0.5 [0.526089311]
199 0.5 0.5 [0.526089311]
299 0.5 0.5 [0.526089311]
399 0.5 0.5 [0.526089311]
499 0.5 0.5 [0.526089311]
599 0.5 0.5 [0.526089311]
699 0.5 0.5 [0.526089311]
799 0.5 0.5 [0.526089311]
899 0.5 0.5 [0.526089311]
999 0.5 0.5 [0.526089311]


In [15]:
# classification with sigmoid activation function: Case 3
x=0; y=1; alpha=0.1
w = tf.random.normal([1],0,1)
b = tf.random.normal([1],0,1)
for i in range(1000):
    output = sigmo(x*w+b)
    error = y - output
    w = w + alpha*error
    b = b+ alpha*error
    if i%100 == 99:
        tf.print(f'{i}, {error:.5f}, {output:.5f}, {w}, {b}')

99, 0.11677, 0.88323, [2.1926222], [2.0350652]
199, 0.05617, 0.94383, [2.9846983], [2.8271413]
299, 0.03653, 0.96347, [3.433557], [3.276]
399, 0.02697, 0.97303, [3.745857], [3.5883]
499, 0.02135, 0.97865, [3.985003], [3.827446]
599, 0.01765, 0.98235, [4.1786304], [4.0210743]
699, 0.01504, 0.98496, [4.3412294], [4.1836734]
799, 0.01309, 0.98691, [4.481335], [4.323779]
899, 0.01159, 0.98841, [4.6043897], [4.4468336]
999, 0.01040, 0.98960, [4.714081], [4.5565248]


## 2. And, Or, Xor

In [19]:
# And classification
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([1,0,0,0])
alpha = 0.1
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)

In [20]:
for i in range(2000):
    error_sum = 0
    for j in range(4):
        output = sigmo(x[j].dot(w)+b) # 입력(x)와 가중치(w) 그리고 편향(b)을 이용하여 출력(output) 계산
        error = y[j] - output # 실제값(y)과 출력(output)의 오차 계산
        w = w + alpha*error*x[j] # 가중치(w) 갱신
        b = b + alpha*error # 편향(b) 갱신
        error_sum += error # 에러의 합을 업데이트합니다.
    if i%200 == 199:
        print(i, error_sum, w.numpy(), b.numpy())

199 -0.10859190811617815 [2.7487965 2.7480726] [-4.371419]
399 -0.06509696806549983 [3.8756626 3.8868809] [-6.032301]
599 -0.04636409075543933 [4.6145144 4.6236963] [-7.1252904]
799 -0.035900353926343005 [5.1624207 5.169754 ] [-7.938705]
999 -0.02923618861172763 [5.596977 5.60301 ] [-8.585288]
1199 -0.0246312097974632 [5.956608  5.9617105] [-9.121166]
1399 -0.021263767681076004 [6.263092 6.267506] [-9.578322]
1599 -0.01869666244412322 [6.5299697 6.533854 ] [-9.976701]
1799 -0.01667567244458324 [6.7662225 6.769687 ] [-10.329577]
1999 -0.015044378928674995 [6.97809   6.9812174] [-10.646181]


In [26]:
for i in range(4):
    print(f'X:{x[i]} Y:{y[i]} Prediction: {sigmo(np.sum(x[i]*w)+b):.5f}')

X:[1 1] Y:1 Prediction: 0.96488
X:[1 0] Y:0 Prediction: 0.02489
X:[0 1] Y:0 Prediction: 0.02497
X:[0 0] Y:0 Prediction: 0.00002


In [ ]:
# Or classification
